### ISSUE TITLE
I am unable to login. Receiving a pink bar with "undefined method '[]' for #Api::RodaRequest POST /api/user/login" message.

### ISSUE THREAD

**Issue by charliewilsonstaindrop** [tobymao/18xx#12139]
**How to Reproduce the Problem?**

What steps cause the unexpected behavior?

e.g.
- Trying to login with my username results in "Access Denied"

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by axsk** [comment]
Can confirm the issue.
On login attempt (after submitting the username/password) theres a red banner on top saying 
```undefined method `[]' for #<Api::RodaRequest POST /api/user/login>```

Browser: Firefox 143.0.4 (private mode - as I did not want to log out of my current session in normal mode)
Platform: Windows Desktop

**Comment by Witzman** [comment]
Can also confirm on ipad.

Also game creation throw error

**Comment by Willempie3** [comment]
I also cannot login anymore with the same error message. Both my accounts fail. The accounts are Richard10 and Willempie3

**Comment by michaeljb** [comment]
This was caused by #12125. Rolling back the rack version caused dependabot to open [#12141](https://github.com/tobymao/18xx/pull/12141), which will require some other changes before we can merge it.
