### ISSUE TITLE
1868 Wyoming - Cannot Load Game

### ISSUE THREAD

**Issue by PNWCornerCase** [tobymao/18xx#11594]
https://18xx.games/game/197458

Operating Round 3 - halfway through I decided to HotSeat the game and check something. After that could not load the regular game.

**Comment by ollybh** [comment]
`undefined method `trains' for <Engine::Company: P6c>`

This error has been caused by PR #11586. That added code to `Round::Operating.setup` to iterate through each entity's trains, marking them as not having operated. However in 1868WY, a company (P6c) is included in the entities and companies do not have a trains property.

@michaeljb Is it correct that P6c is included in the operating round entities? I don't know the 1868WY rules at all.

CC: @crericha.

**Comment by BellmakerSA** [comment]
![Image](https://github.com/user-attachments/assets/83034b97-1a97-4daa-8cf4-14491018e4ca)

This is P6c it doesn’t seem like it needs to be there?
